#+title: agitate: Extras for diff-mode, vc-git, log-edit, log-view
#+author: Protesilaos Stavrou
#+email: info@protesilaos.com
#+language: en
#+options: ':t toc:nil author:t email:t num:t
#+startup: content
#+macro: stable-version 0.0.0
#+macro: release-date N/A
#+macro: development-version 0.1.0-dev
#+export_file_name: agitate.texi
#+texinfo_filename: agitate.info
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: Agitate: (agitate)
#+texinfo_dir_desc: Extras for diff-mode, vc-git, log-edit, log-view
#+texinfo_header: @set MAINTAINERSITE @uref{https://protesilaos.com,maintainer webpage}
#+texinfo_header: @set MAINTAINER Protesilaos Stavrou
#+texinfo_header: @set MAINTAINEREMAIL @email{info@protesilaos.com}
#+texinfo_header: @set MAINTAINERCONTACT @uref{mailto:info@protesilaos.com,contact the maintainer}

#+texinfo: @insertcopying

This manual, written by Protesilaos Stavrou, describes the customization
options for the Emacs package called =agitate= (or =agitate.el=), and
provides every other piece of information pertinent to it.

The documentation furnished herein corresponds to stable version
{{{stable-version}}}, released on {{{release-date}}}.  Any reference to
a newer feature which does not yet form part of the latest tagged
commit, is explicitly marked as such.

Current development target is {{{development-version}}}.

+ Package name (GNU ELPA): =agitate=
+ Official manual: <https://protesilaos.com/emacs/agitate>
+ Git repositories:
  + GitHub: <https://github.com/protesilaos/agitate>
  + GitLab: <https://gitlab.com/protesilaos/agitate>
+ Backronym: Another Git Interface Trying to Agitate Tranquil Emacsers.

If you are viewing the README.org version of this file, please note that
the GNU ELPA machinery automatically generates an Info manual out of it.

#+toc: headlines 8 insert TOC here, with eight headline levels

* Overview
:PROPERTIES:
:CUSTOM_ID: h:0a38126c-ebd0-4157-8af1-4b5bf259d685
:END:

Agitate is a collection of commands or potentially useful functions
that expand on the available version control features of Emacs.  Those
are meant to complement a workflow that relies on the built-in Version
Control framework and its accoutrements (=diff-mode.el=,
=log-view.el=, =log-edit.el=, =vc-git.el=, and potentially others).

The following sections document the extras per their scope.

** Extras for diff-mode
:PROPERTIES:
:CUSTOM_ID: h:ef659174-f1fe-46c9-ab2a-9089529ba0ac
:END:

#+findex: agitate-diff-refine-cycle
+ Function ~agitate-diff-refine-cycle~ :: Cycle current, all, or no
  refined (word-wise) diff highlighting.  Upon first invocation,
  refine the diff hunk at point or, when none exists, the one closest
  to it.  On second call, operate on the entire buffer.  And on the
  third time, remove all word-wise fontification.

#+findex: agitate-diff-buffer-or-file
+ Function ~agitate-diff-buffer-or-file~ :: Produce a diff against the
  file or latest revision.  If the buffer is modified, produce a diff
  that compares its state to that of the corresponding file.  In
  simple terms, show the latest unsaved changes. If the buffer is not
  modified, produce a diff of the file relative to its latest
  revision.

#+findex: agitate-diff-narrow-dwim
+ Function ~agitate-diff-narrow-dwim~ :: Narrow to diff hunk or file
  and widen when already narrowed.  By default narrow to the focused
  diff hunk.  With optional =NARROW-FILE= as a prefix argument,
  operate on the current file instead.

#+findex: agitate-diff-enable-outline-minor-mode
+ Function ~agitate-diff-enable-outline-minor-mode~ :: Enable
  ~outline-minor-mode~ with appropriate tweaks for diffs.  This
  basically gives you folding of diff hunks by means of the
  ~outline-cycle~ command. Add this function to the ~diff-mode-hook~.

** Extras for log-edit
:PROPERTIES:
:CUSTOM_ID: h:7b9679c7-1313-4f40-bfbf-2cabca2d3549
:END:

#+findex: agitate-log-edit-insert-file-name
+ Function ~agitate-log-edit-insert-file-name~ :: Insert at point file
  name sans directory from ~log-edit-files~.  If multiple files are
  involved, prompt with completion for one among them. With optional
  prefix argument =WITH-FILE-EXTENSION=, include the file extension.
  Else omit it.

#+findex: agitate-log-edit-emoji-commit
+ Function ~agitate-log-edit-emoji-commit~ :: Insert =EMOJI-COMMIT=
  message at point.  When called interactively, prompt for
  =EMOJI-COMMIT= among the ~agitate-log-edit-emoji-collection~.

#+vindex: agitate-log-edit-emoji-collection
+ Variable ~agitate-log-edit-emoji-collection~ :: User option whose
  value is a list of strings that represent completion candidates for
  ~agitate-log-edit-emoji-commit~.  It is recommended to use the
  =:EMOJI:= notation, as it works even in terminals that cannot output
  Unicode.  Relevant applications will render those as their
  corresponding graphical emoji.

#+findex: agitate-log-edit-conventional-commit
+ Function ~agitate-log-edit-conventional-commit~ :: Insert
  conventional commit message at point.  Prompt for entry among those
  declared in ~agitate-log-edit-conventional-commits-collection~.

#+vindex: agitate-log-edit-conventional-commits-collection
+ Variable ~agitate-log-edit-conventional-commits-collection~ :: User
  options whose value is a list of strings that represent completion
  candidates for ~agitate-log-edit-conventional-commit~.

The emoji commits are inspired by <https://gitmoji.dev/>, though I
think most of those are superfluous.  Less is more.  The "conventional
commits" are documented here: <https://www.conventionalcommits.org/en/v1.0.0/>.

*** Informative log-edit window configuration mode
:PROPERTIES:
:CUSTOM_ID: h:7f50cff1-4abd-4155-a57b-07f283db7630
:END:

#+findex: agitate-log-edit-informative-mode
#+vindex: agitate-log-edit-informative-mode
The ~agitate-log-edit-informative-mode~ is a global minor mode that
rearranges the window configuration (layout) when bringing up a
~log-edit~ buffer (such as what happens when =C-x v v=
(~vc-next-action~) is about to commit the changes).  It shows the
~log-edit~ buffer on the left and the corresponding diff on the right.

#+vindex: agitate-log-edit-informative-show-files
When the user option ~agitate-log-edit-informative-show-files~ is
non-nil (the default), the list of files pertinent to the current
action is shown below the ~log-edit~ buffer.

#+vindex: agitate-log-edit-informative-show-root-log
#+vindex: agitate-log-limit
When the user option ~agitate-log-edit-informative-show-root-log~ is
non-nil, the root log of the revisions is shown below the window that
displays the ~log-edit~ buffer.  Its contents are bound by the value
of the user option ~agitate-log-limit~.

** Extras for log-view
:PROPERTIES:
:CUSTOM_ID: h:2a48ff74-6a8f-4fc6-9e14-c9e412857b2d
:END:

#+findex: agitate-log-view-kill-revision
+ Function ~agitate-log-view-kill-revision~ :: Append to ~kill-ring~
  log-view revision at or around point.  When the log-view is in the
  short format (one compact line per revision), the revision is the
  one on the current line.  If the revision is expanded with
  ~log-view-expanded-log-entry-function~ and point is somewhere inside
  the expanded text, the revision is still the same. When the log-view
  is in the long format (detailed view where each revision spans
  several lines), the revision is the one pertinent to the text at
  point.

#+findex: agitate-log-view-kill-revision-expanded
+ Function ~agitate-log-view-kill-revision-expanded~ :: Append to
  ~kill-ring~ expanded message of log-view revision at point
  (developers can also check the private functions it uses).

** Extras for vc-git
:PROPERTIES:
:CUSTOM_ID: h:f1a1f462-b6db-415a-b8e6-ba23788cb6e3
:END:

#+findex: agitate-vc-git-find-revision
+ Function ~agitate-vc-git-find-revision~ :: Find revision of current
  file, visiting it in a buffer.  Prompt with completion for the
  revision.  The number of revisions in the log is controlled by the
  user option ~agitate-log-limit~.  Pro tip: if you are using the
  =embark= package, you can produce a snapshot of the minibuffer
  prompt.  Then use the resulting buffer to browse through the file's
  history.

#+findex: agitate-vc-git-show
#+vindex: agitate-log-limit
+ Function ~agitate-vc-git-show~ :: Prompt for commit and run
  =git-show(1)= on it. With optional =CURRENT-FILE= as prefix
  argument, limit the commits to those pertaining to the current file.
  The number of revisions in the log is controlled by the user option
  ~agitate-log-limit~.  Pro tip: if you are using the =embark=
  package, you can produce a snapshot of the minibuffer prompt.  Then
  use the resulting buffer to browse through the available commits.

#+findex: agitate-vc-git-show-tag
+ Function ~agitate-vc-git-show-tag~ :: Run =git-show(1)= on Git
  =TAG=.  When called interactively, prompt for TAG using minibuffer
  completion.  Pro tip: if you are using the =embark= package, you can
  produce a snapshot of the minibuffer prompt.  Then use the resulting
  buffer to browse through the available tags.

#+findex: agitate-vc-git-format-patch-single
+ Function ~agitate-vc-git-format-patch-single~ :: Format patch for a
  single =COMMIT=.  If in a log-view buffer, the =COMMIT= is the one
  at point.  For the details of how that is determined, read the doc
  string of ~agitate-log-view-kill-revision~.  If there is no such
  commit at point, prompt for =COMMIT= using minibuffer completion.
  Output the patch file to the return value of the function
  ~vc-root-dir~.  The number of revisions in the log is controlled by
  the user option ~agitate-log-limit~.  For Emacs 29, consider using
  ~vc-prepare-patch~.  Relevant except from the source code:

  #+begin_src emacs-lisp
  ;; TODO 2022-09-27: Handle the output directory better.  Though I am
  ;; not sure how people work with those.  I normally use the root of
  ;; the current repo (and then clean it) or put everything in the
  ;; ~/Desktop or some dedicated "patches" directory.
  #+end_src

#+findex: agitate-vc-git-format-patch-n-from-head
+ Function ~agitate-vc-git-format-patch-n-from-head~ :: Format patches
  covering =NUMBER= of commits from current HEAD.  This is the
  eqvuivalent of: =git format-patch -NUMBER=.  For Emacs 29, consider
  using ~vc-prepare-patch~.

#+findex: agitate-vc-git-grep
+ Function ~agitate-vc-git-grep~ :: Run =git-grep(1)= for =REGEXP= in
  ~vc-root-dir~.  This is a simple wrapper around ~vc-git-grep~ to
  streamline the basic task of searching for a regexp in the current
  Git repository.  Use the original ~vc-git-grep~ for its other
  arguments.

#+findex: agitate-vc-git-kill-commit-hash
+ Function ~agitate-vc-git-kill-commit-hash~ :: Append to ~kill-ring~
  hash of commit.  Prompt for commit using minibuffer completion.  The
  number of revisions in the log is controlled by the user option
  ~agitate-log-limit~.  To kill the message of the commit, use the
  command ~agitate-vc-git-kill-commit-message~.

#+findex: agitate-vc-git-kill-commit-message
+ Function ~agitate-vc-git-kill-commit-message~ :: Append to
  ~kill-ring~ message of commit with =HASH= identifier.  When called
  interactively, prompt for =HASH= using minibuffer completion.  When
  point is in a log-view buffer, make the revision at point the
  default value of the prompt (though also see the command
  ~agitate-log-view-kill-revision-expanded~).  The number of revisions
  in the log is controlled by the user option ~agitate-log-limit~.  To
  kill only the commit hash, use the command
  ~agitate-vc-git-kill-commit-hash~.

#+findex: agitate-vc-git-push-prompt-for-remote
+ Function ~agitate-vc-git-push-prompt-for-remote~ :: Behave like
  ~vc-git-push~ but prompt for a remote, if needed.  The meaning of
  =PROMPT= is the same as that of ~vc-git-push~.  In such a case, do
  not prompt for a remote. To use this function add it as an override
  advice to ~vc-git-push~.  Relevant quote from the source code:

  #+begin_src emacs-lisp
  ;; TODO 2022-09-27: We can have something similar which prompts for a
  ;; branch to push to.  There are lots of possibilities.  The idea is
  ;; that the user can pick the function they are most likely to use as
  ;; their default.  Then they can rely on PROMPT to modify its
  ;; behaviour.
  #+end_src

* Installation
:PROPERTIES:
:CUSTOM_ID: h:ac33de13-bc87-4d3b-be69-dec64aa7faa2
:END:
#+cindex: Installation instructions

** GNU ELPA package
:PROPERTIES:
:CUSTOM_ID: h:068fe283-a5ee-4bbc-8ea0-c2413794b6b2
:END:

The package is available as =agitate=.  Simply do:

: M-x package-refresh-contents
: M-x package-install

And search for it.

GNU ELPA provides the latest stable release.  Those who prefer to follow
the development process in order to report bugs or suggest changes, can
use the version of the package from the GNU-devel ELPA archive.  Read:
https://protesilaos.com/codelog/2022-05-13-emacs-elpa-devel/.

** Manual installation
:PROPERTIES:
:CUSTOM_ID: h:deaaba28-9236-45b8-925b-1e35ff78d2a0
:END:

Assuming your Emacs files are found in =~/.emacs.d/=, execute the
following commands in a shell prompt:

#+begin_src sh
cd ~/.emacs.d

# Create a directory for manually-installed packages
mkdir manual-packages

# Go to the new directory
cd manual-packages

# Clone this repo, naming it "agitate"
git clone https://git.sr.ht/~protesilaos/agitate agitate
#+end_src

Finally, in your =init.el= (or equivalent) evaluate this:

#+begin_src emacs-lisp
;; Make Elisp files in that directory available to the user.
(add-to-list 'load-path "~/.emacs.d/manual-packages/agitate")
#+end_src

Everything is in place to set up the package.

* Sample configuration
:PROPERTIES:
:CUSTOM_ID: h:9ea57def-7883-44bd-b27e-54127457b808
:END:

#+begin_src emacs-lisp
;; These are all OPTIONAL.  You should just use whatever key bindings
;; or setup you prefer.

;; Agitate is still a WORK-IN-PROGRESS.

(require 'agitate)

(add-hook 'diff-mode-hook #'agitate-diff-enable-outline-minor-mode)

(advice-add #'vc-git-push :override #'agitate-vc-git-push-prompt-for-remote)

;; Also check: `agitate-log-edit-informative-show-files',
;; `agitate-log-edit-informative-show-root-log'.
(agitate-log-edit-informative-mode 1)

(let ((map global-map))
  (define-key map (kbd "C-x v =") #'agitate-diff-buffer-or-file) ; replace `vc-diff'
  (define-key map (kbd "C-x v g") #'agitate-vc-git-grep) ; replace `vc-annotate'
  (define-key map (kbd "C-x v f") #'agitate-vc-git-find-revision)
  (define-key map (kbd "C-x v s") #'agitate-vc-git-show)
  (define-key map (kbd "C-x v p p") #'agitate-vc-git-format-patch-single)
  (define-key map (kbd "C-x v p n") #'agitate-vc-git-format-patch-n-from-head))
(let ((map diff-mode-map))
  (define-key map (kbd "C-c C-b") #'agitate-diff-refine-cycle) ; replace `diff-refine-hunk'
  (define-key map (kbd "C-c C-n") #'agitate-diff-narrow-dwim))
(let ((map log-view-mode-map))
  (define-key map (kbd "w") #'agitate-log-view-kill-revision)
  (define-key map (kbd "W") #'agitate-log-view-kill-revision-expanded))
(let ((map vc-git-log-view-mode-map))
  (define-key map (kbd "c") #'agitate-vc-git-format-patch-single))
(let ((map log-edit-mode-map))
  (define-key map (kbd "C-c C-i C-n") #'agitate-log-edit-insert-file-name)
  ;; See user options `agitate-log-edit-emoji-collection' and
  ;; `agitate-log-edit-conventional-commits-collection'.
  (define-key map (kbd "C-c C-i C-e") #'agitate-log-edit-emoji-commit)
  (define-key map (kbd "C-c C-i C-c") #'agitate-log-edit-conventional-commit))
#+end_src

* COPYING
:PROPERTIES:
:CUSTOM_ID: h:22035775-da3a-4f11-b078-bbe76ef8a93b
:END:

Copyright (C) 2022-2023  Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* GNU Free Documentation License
:PROPERTIES:
:CUSTOM_ID: h:0f9a759f-89f7-4242-b484-e0d4bf8aef09
:END:

#+texinfo: @include doclicense.texi

#+begin_export html
<pre>

                GNU Free Documentation License
                 Version 1.3, 3 November 2008


 Copyright (C) 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
     <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other
functional and useful document "free" in the sense of freedom: to
assure everyone the effective freedom to copy and redistribute it,
with or without modifying it, either commercially or noncommercially.
Secondarily, this License preserves for the author and publisher a way
to get credit for their work, while not being considered responsible
for modifications made by others.

This License is a kind of "copyleft", which means that derivative
works of the document must themselves be free in the same sense.  It
complements the GNU General Public License, which is a copyleft
license designed for free software.

We have designed this License in order to use it for manuals for free
software, because free software needs free documentation: a free
program should come with manuals providing the same freedoms that the
software does.  But this License is not limited to software manuals;
it can be used for any textual work, regardless of subject matter or
whether it is published as a printed book.  We recommend this License
principally for works whose purpose is instruction or reference.


1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that
contains a notice placed by the copyright holder saying it can be
distributed under the terms of this License.  Such a notice grants a
world-wide, royalty-free license, unlimited in duration, to use that
work under the conditions stated herein.  The "Document", below,
refers to any such manual or work.  Any member of the public is a
licensee, and is addressed as "you".  You accept the license if you
copy, modify or distribute the work in a way requiring permission
under copyright law.

A "Modified Version" of the Document means any work containing the
Document or a portion of it, either copied verbatim, or with
modifications and/or translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of
the Document that deals exclusively with the relationship of the
publishers or authors of the Document to the Document's overall
subject (or to related matters) and contains nothing that could fall
directly within that overall subject.  (Thus, if the Document is in
part a textbook of mathematics, a Secondary Section may not explain
any mathematics.)  The relationship could be a matter of historical
connection with the subject or with related matters, or of legal,
commercial, philosophical, ethical or political position regarding
them.

The "Invariant Sections" are certain Secondary Sections whose titles
are designated, as being those of Invariant Sections, in the notice
that says that the Document is released under this License.  If a
section does not fit the above definition of Secondary then it is not
allowed to be designated as Invariant.  The Document may contain zero
Invariant Sections.  If the Document does not identify any Invariant
Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed,
as Front-Cover Texts or Back-Cover Texts, in the notice that says that
the Document is released under this License.  A Front-Cover Text may
be at most 5 words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy,
represented in a format whose specification is available to the
general public, that is suitable for revising the document
straightforwardly with generic text editors or (for images composed of
pixels) generic paint programs or (for drawings) some widely available
drawing editor, and that is suitable for input to text formatters or
for automatic translation to a variety of formats suitable for input
to text formatters.  A copy made in an otherwise Transparent file
format whose markup, or absence of markup, has been arranged to thwart
or discourage subsequent modification by readers is not Transparent.
An image format is not Transparent if used for any substantial amount
of text.  A copy that is not "Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain
ASCII without markup, Texinfo input format, LaTeX input format, SGML
or XML using a publicly available DTD, and standard-conforming simple
HTML, PostScript or PDF designed for human modification.  Examples of
transparent image formats include PNG, XCF and JPG.  Opaque formats
include proprietary formats that can be read and edited only by
proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the
machine-generated HTML, PostScript or PDF produced by some word
processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself,
plus such following pages as are needed to hold, legibly, the material
this License requires to appear in the title page.  For works in
formats which do not have any title page as such, "Title Page" means
the text near the most prominent appearance of the work's title,
preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of
the Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose
title either is precisely XYZ or contains XYZ in parentheses following
text that translates XYZ in another language.  (Here XYZ stands for a
specific section name mentioned below, such as "Acknowledgements",
"Dedications", "Endorsements", or "History".)  To "Preserve the Title"
of such a section when you modify the Document means that it remains a
section "Entitled XYZ" according to this definition.

The Document may include Warranty Disclaimers next to the notice which
states that this License applies to the Document.  These Warranty
Disclaimers are considered to be included by reference in this
License, but only as regards disclaiming warranties: any other
implication that these Warranty Disclaimers may have is void and has
no effect on the meaning of this License.

2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either
commercially or noncommercially, provided that this License, the
copyright notices, and the license notice saying this License applies
to the Document are reproduced in all copies, and that you add no
other conditions whatsoever to those of this License.  You may not use
technical measures to obstruct or control the reading or further
copying of the copies you make or distribute.  However, you may accept
compensation in exchange for copies.  If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and
you may publicly display copies.


3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have
printed covers) of the Document, numbering more than 100, and the
Document's license notice requires Cover Texts, you must enclose the
copies in covers that carry, clearly and legibly, all these Cover
Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
the back cover.  Both covers must also clearly and legibly identify
you as the publisher of these copies.  The front cover must present
the full title with all words of the title equally prominent and
visible.  You may add other material on the covers in addition.
Copying with changes limited to the covers, as long as they preserve
the title of the Document and satisfy these conditions, can be treated
as verbatim copying in other respects.

If the required texts for either cover are too voluminous to fit
legibly, you should put the first ones listed (as many as fit
reasonably) on the actual cover, and continue the rest onto adjacent
pages.

If you publish or distribute Opaque copies of the Document numbering
more than 100, you must either include a machine-readable Transparent
copy along with each Opaque copy, or state in or with each Opaque copy
a computer-network location from which the general network-using
public has access to download using public-standard network protocols
a complete Transparent copy of the Document, free of added material.
If you use the latter option, you must take reasonably prudent steps,
when you begin distribution of Opaque copies in quantity, to ensure
that this Transparent copy will remain thus accessible at the stated
location until at least one year after the last time you distribute an
Opaque copy (directly or through your agents or retailers) of that
edition to the public.

It is requested, but not required, that you contact the authors of the
Document well before redistributing any large number of copies, to
give them a chance to provide you with an updated version of the
Document.


4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under
the conditions of sections 2 and 3 above, provided that you release
the Modified Version under precisely this License, with the Modified
Version filling the role of the Document, thus licensing distribution
and modification of the Modified Version to whoever possesses a copy
of it.  In addition, you must do these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct
   from that of the Document, and from those of previous versions
   (which should, if there were any, be listed in the History section
   of the Document).  You may use the same title as a previous version
   if the original publisher of that version gives permission.
B. List on the Title Page, as authors, one or more persons or entities
   responsible for authorship of the modifications in the Modified
   Version, together with at least five of the principal authors of the
   Document (all of its principal authors, if it has fewer than five),
   unless they release you from this requirement.
C. State on the Title page the name of the publisher of the
   Modified Version, as the publisher.
D. Preserve all the copyright notices of the Document.
E. Add an appropriate copyright notice for your modifications
   adjacent to the other copyright notices.
F. Include, immediately after the copyright notices, a license notice
   giving the public permission to use the Modified Version under the
   terms of this License, in the form shown in the Addendum below.
G. Preserve in that license notice the full lists of Invariant Sections
   and required Cover Texts given in the Document's license notice.
H. Include an unaltered copy of this License.
I. Preserve the section Entitled "History", Preserve its Title, and add
   to it an item stating at least the title, year, new authors, and
   publisher of the Modified Version as given on the Title Page.  If
   there is no section Entitled "History" in the Document, create one
   stating the title, year, authors, and publisher of the Document as
   given on its Title Page, then add an item describing the Modified
   Version as stated in the previous sentence.
J. Preserve the network location, if any, given in the Document for
   public access to a Transparent copy of the Document, and likewise
   the network locations given in the Document for previous versions
   it was based on.  These may be placed in the "History" section.
   You may omit a network location for a work that was published at
   least four years before the Document itself, or if the original
   publisher of the version it refers to gives permission.
K. For any section Entitled "Acknowledgements" or "Dedications",
   Preserve the Title of the section, and preserve in the section all
   the substance and tone of each of the contributor acknowledgements
   and/or dedications given therein.
L. Preserve all the Invariant Sections of the Document,
   unaltered in their text and in their titles.  Section numbers
   or the equivalent are not considered part of the section titles.
M. Delete any section Entitled "Endorsements".  Such a section
   may not be included in the Modified Version.
N. Do not retitle any existing section to be Entitled "Endorsements"
   or to conflict in title with any Invariant Section.
O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or
appendices that qualify as Secondary Sections and contain no material
copied from the Document, you may at your option designate some or all
of these sections as invariant.  To do this, add their titles to the
list of Invariant Sections in the Modified Version's license notice.
These titles must be distinct from any other section titles.

You may add a section Entitled "Endorsements", provided it contains
nothing but endorsements of your Modified Version by various
parties--for example, statements of peer review or that the text has
been approved by an organization as the authoritative definition of a
standard.

You may add a passage of up to five words as a Front-Cover Text, and a
passage of up to 25 words as a Back-Cover Text, to the end of the list
of Cover Texts in the Modified Version.  Only one passage of
Front-Cover Text and one of Back-Cover Text may be added by (or
through arrangements made by) any one entity.  If the Document already
includes a cover text for the same cover, previously added by you or
by arrangement made by the same entity you are acting on behalf of,
you may not add another; but you may replace the old one, on explicit
permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License
give permission to use their names for publicity for or to assert or
imply endorsement of any Modified Version.


5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this
License, under the terms defined in section 4 above for modified
versions, provided that you include in the combination all of the
Invariant Sections of all of the original documents, unmodified, and
list them all as Invariant Sections of your combined work in its
license notice, and that you preserve all their Warranty Disclaimers.

The combined work need only contain one copy of this License, and
multiple identical Invariant Sections may be replaced with a single
copy.  If there are multiple Invariant Sections with the same name but
different contents, make the title of each such section unique by
adding at the end of it, in parentheses, the name of the original
author or publisher of that section if known, or else a unique number.
Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History"
in the various original documents, forming one section Entitled
"History"; likewise combine any sections Entitled "Acknowledgements",
and any sections Entitled "Dedications".  You must delete all sections
Entitled "Endorsements".


6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other
documents released under this License, and replace the individual
copies of this License in the various documents with a single copy
that is included in the collection, provided that you follow the rules
of this License for verbatim copying of each of the documents in all
other respects.

You may extract a single document from such a collection, and
distribute it individually under this License, provided you insert a
copy of this License into the extracted document, and follow this
License in all other respects regarding verbatim copying of that
document.


7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate
and independent documents or works, in or on a volume of a storage or
distribution medium, is called an "aggregate" if the copyright
resulting from the compilation is not used to limit the legal rights
of the compilation's users beyond what the individual works permit.
When the Document is included in an aggregate, this License does not
apply to the other works in the aggregate which are not themselves
derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these
copies of the Document, then if the Document is less than one half of
the entire aggregate, the Document's Cover Texts may be placed on
covers that bracket the Document within the aggregate, or the
electronic equivalent of covers if the Document is in electronic form.
Otherwise they must appear on printed covers that bracket the whole
aggregate.


8. TRANSLATION

Translation is considered a kind of modification, so you may
distribute translations of the Document under the terms of section 4.
Replacing Invariant Sections with translations requires special
permission from their copyright holders, but you may include
translations of some or all Invariant Sections in addition to the
original versions of these Invariant Sections.  You may include a
translation of this License, and all the license notices in the
Document, and any Warranty Disclaimers, provided that you also include
the original English version of this License and the original versions
of those notices and disclaimers.  In case of a disagreement between
the translation and the original version of this License or a notice
or disclaimer, the original version will prevail.

If a section in the Document is Entitled "Acknowledgements",
"Dedications", or "History", the requirement (section 4) to Preserve
its Title (section 1) will typically require changing the actual
title.


9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document
except as expressly provided under this License.  Any attempt
otherwise to copy, modify, sublicense, or distribute it is void, and
will automatically terminate your rights under this License.

However, if you cease all violation of this License, then your license
from a particular copyright holder is reinstated (a) provisionally,
unless and until the copyright holder explicitly and finally
terminates your license, and (b) permanently, if the copyright holder
fails to notify you of the violation by some reasonable means prior to
60 days after the cessation.

Moreover, your license from a particular copyright holder is
reinstated permanently if the copyright holder notifies you of the
violation by some reasonable means, this is the first time you have
received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

Termination of your rights under this section does not terminate the
licenses of parties who have received copies or rights from you under
this License.  If your rights have been terminated and not permanently
reinstated, receipt of a copy of some or all of the same material does
not give you any rights to use it.


10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the
GNU Free Documentation License from time to time.  Such new versions
will be similar in spirit to the present version, but may differ in
detail to address new problems or concerns.  See
https://www.gnu.org/licenses/.

Each version of the License is given a distinguishing version number.
If the Document specifies that a particular numbered version of this
License "or any later version" applies to it, you have the option of
following the terms and conditions either of that specified version or
of any later version that has been published (not as a draft) by the
Free Software Foundation.  If the Document does not specify a version
number of this License, you may choose any version ever published (not
as a draft) by the Free Software Foundation.  If the Document
specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a
version permanently authorizes you to choose that version for the
Document.

11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any
World Wide Web server that publishes copyrightable works and also
provides prominent facilities for anybody to edit those works.  A
public wiki that anybody can edit is an example of such a server.  A
"Massive Multiauthor Collaboration" (or "MMC") contained in the site
means any set of copyrightable works thus published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0
license published by Creative Commons Corporation, a not-for-profit
corporation with a principal place of business in San Francisco,
California, as well as future copyleft versions of that license
published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in
part, as part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this
License, and if all works that were first published under this License
somewhere other than this MMC, and subsequently incorporated in whole or
in part into the MMC, (1) had no cover texts or invariant sections, and
(2) were thus incorporated prior to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site
under CC-BY-SA on the same site at any time before August 1, 2009,
provided the MMC is eligible for relicensing.


ADDENDUM: How to use this License for your documents

To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and
license notices just after the title page:

    Copyright (c)  YEAR  YOUR NAME.
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in the section entitled "GNU
    Free Documentation License".

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the "with...Texts." line with this:

    with the Invariant Sections being LIST THEIR TITLES, with the
    Front-Cover Texts being LIST, and with the Back-Cover Texts being LIST.

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of
free software license, such as the GNU General Public License,
to permit their use in free software.
</pre>
#+end_export

#+html: <!--

* Indices
:PROPERTIES:
:CUSTOM_ID: h:85a055ac-2a38-4f1f-89ad-6dad5ebc4e5e
:END:

** Function index
:PROPERTIES:
:INDEX: fn
:CUSTOM_ID: h:65c633ca-fee6-402c-b85c-38f732e91f66
:END:

** Variable index
:PROPERTIES:
:INDEX: vr
:CUSTOM_ID: h:f8ae2926-fb9b-431f-ad31-d5f50f0f6e53
:END:

** Concept index
:PROPERTIES:
:INDEX: cp
:CUSTOM_ID: h:25946034-715f-467f-bef1-6a0445d53326
:END:

#+html: -->
